import WorkoutProvider from "@/context/WorkoutProvider";
import { Inter, Oswald } from "next/font/google";
import Navbar from "./components/shared/Navbar";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/shared/Footer";

// Font configuration
export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

// Metadata configuration
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * ==========================
 * RootLayout Component
 * ==========================
 */

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-950">
        <WorkoutProvider>
          <Navbar />
          <div>{children}</div>
          <Footer />
        </WorkoutProvider>
      </body>
    </html>
  );
}
